- job:
    name: tox-pre-commit
    parent: tox
    vars:
      tox_envlist: pre-commit
      python_version: 3.8
      python_use_pyenv: true
- job:
    name: tox-setup-check
    parent: tox
    vars:
      tox_envlist: setup-check

- job:
    name: tox-py27-setup-check
    vars:
      tox_envlist: setup-check
      python_version: 2.7
      python_use_pyenv: false
    parent: tox

- job:
    name: tox-py35-setup-check
    vars:
      tox_envlist: setup-check
      python_version: 3.5
      python_use_pyenv: true
    parent: tox

- job:
    name: tox-py36-setup-check
    vars:
      tox_envlist: setup-check
      python_version: 3.6
      python_use_pyenv: true
    parent: tox

- job:
    name: tox-py37-setup-check
    vars:
      tox_envlist: setup-check
      python_version: 3.7
      python_use_pyenv: false
    parent: tox

- job:
    name: tox-py38-setup-check
    vars:
      tox_envlist: setup-check
      python_version: 3.8
      python_use_pyenv: true
    parent: tox

- job:
    name: tox-build-docs
    parent: tox
    vars:
      tox_envlist: build-docs
      python_version: 3.8
      python_use_pyenv: true

- job:
    name: tox-spellcheck-docs
    parent: tox
    vars:
      tox_envlist: spellcheck-docs
      python_version: 3.8
      python_use_pyenv: true

- job:
    name: tox-linkcheck-docs
    parent: tox
    vars:
      tox_envlist: linkcheck-docs
      python_version: 3.8
      python_use_pyenv: true

- job:
    name: tox-pre-commit-failing
    parent: tox
    voting: false
    vars:
      tox_envlist: pre-commit-failing
      python_version: 3.8
      python_use_pyenv: true

- project:
    check:
      jobs:
      - tox-pre-commit
      - tox-py27-setup-check
      - tox-py35-setup-check
      - tox-py36-setup-check
      - tox-py37-setup-check
      - tox-py38-setup-check
      - tox-build-docs
      - tox-spellcheck-docs
      - tox-linkcheck-docs
      - tox-pre-commit-failing
