- job:
    name: tox-pre-commit
    parent: tox
    vars:
      tox_envlist: pre-commit
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- job:
    name: tox-setup-check
    parent: tox
    vars:
      tox_envlist: setup-check
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- job:
    name: tox-build-docs
    parent: tox
    vars:
      tox_envlist: build-docs
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- job:
    name: tox-spellcheck-docs
    parent: tox
    vars:
      tox_envlist: spellcheck-docs
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- job:
    name: tox-linkcheck-docs
    parent: tox
    vars:
      tox_envlist: linkcheck-docs
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- job:
    name: tox-pre-commit-failing
    parent: tox
    voting: false
    vars:
      tox_envlist: pre-commit-failing
      # NOTE(mnaser): Drop this once zuul/zuul-jobs no longer prefers
      #               Python 2 by default.
      tox_prefer_python2: false

- project:
    check:
      jobs:
      - tox-pre-commit
      - tox-setup-check
      - tox-build-docs
      - tox-spellcheck-docs
      - tox-linkcheck-docs
      - tox-pre-commit-failing
