import typing as _t

class MaxSizeExceeded(Exception): ...
class NoSSLError(Exception): ...
class FatalSSLAlert(Exception): ...

def plat_specific_errors(*errnames: str) -> list[int]: ...

socket_error_eintr: list[int]
socket_errors_to_ignore: list[int]
socket_errors_nonblocking: list[int]
acceptable_sock_shutdown_error_codes: set[int]
acceptable_sock_shutdown_exceptions: tuple[_t.Type[Exception], ...]
