blank_issues_enabled: false
contact_links:
  - name: 💼 For Enterprise
    url: https://tidelift.com/subscription/pkg/pypi-cheroot?utm_source=pypi-cheroot&utm_medium=referral&utm_campaign=github
    about: Cheroot is available as part of the Tidelift Subscription.
  - name: 💬 Gitter Chat
    url: https://gitter.im/cherrypy/cherrypy
    about: Please ask and answer usage questions here.
  - name: 🤷💻🤦 StackOverflow
    url: https://stackoverflow.com/questions/tagged/cheroot+or+cherrypy
    about: Please ask typical Q&A here.
