from . import Adapter
from ..makefile import StreamReader, StreamWriter
from OpenSSL import SSL

ssl_conn_type: SSL.Connection

class SSLFileobjectMixin:
    ssl_timeout: int
    ssl_retry: float
    def recv(self, size): ...
    def readline(self, size: int = ...): ...
    def sendall(self, *args, **kwargs): ...
    def send(self, *args, **kwargs): ...

class SSLFileobjectStreamReader(SSLFileobjectMixin, StreamReader): ...
class SSLFileobjectStreamWriter(SSLFileobjectMixin, StreamWriter): ...

class SSLConnectionProxyMeta:
    def __new__(mcl, name, bases, nmspc): ...

class SSLConnection():
    def __init__(self, *args) -> None: ...

class pyOpenSSLAdapter(Adapter):
    ...